### ISSUE TITLE
图片分组，删除单个，图片下标错误

### ISSUE THREAD

**Issue by Mori-his** [ssshooter/img-vuer#12]
问题：当一个图片分组之后，有删除操作，你的unbind获取的el不是当前删除的el是最后一个el
我的分析：VUE在>=2.0之后是虚拟DOM,虚拟DOM的优点之一是操作最少的DOM节点来完成需求，减少重复渲染，当我在操作图片分组的时候我的图片组是一个数组，当我删除一个图片的时候，我只需要删除数据源即可（这就叫数据驱动了），然后虚拟DOM一比对只是移除了一个数据，然而它只是把列表的最后一个DOM节点，不管你删除的下标是几，都是remove 最后一个el,  这就是问题的所在了, 这就是为什么unbind里的El返回的总数图片组里的最后一个了。

有时间我在思考这个问题，最后这种删除的暂时不做分组了
mail: zhangss5210@163.com

**Comment by ssshooter** [comment]
@Mori-his 删除操作是如何进行的？

**Comment by Mori-his** [comment]
我用this.imgs.splice(index, 1)做过删除，也重新赋值过，这两种测试都试了，结果是一样的，unbind的el参数返回的是imgs输出到真实DOM里的最后一个元素

**Comment by ssshooter** [comment]
😹 我这边测试 splice 好像没问题啊，list1.splice(1,1) 确实是删掉第二张图片

**Comment by Mori-his** [comment]
我写的是一个上传功能，而且有点负责，图片组是自动生成的，为了能每次删除之后要把img的自定义索引重置一下，所以每一次当图片列表被删除一张我就会更新下图片列表，然后就给当前的imgs重新赋值了一遍，举例：
`
data() {
  return {
    imgs: ["imgSrc1", "imgSrc2", "imgSrc3", "imgSrc4",]
  };
}
mounted() {
  this.imgs.splice(1, 1);
}

{
 unbind(el, {value, arg}) {
     // 这里的el.src 应该等于imgSrc2   但是等于了imgSrc4
     const group = arg || value;
     /**
      *    ........ 
      */
     if(group) {
      let imgGroup = imgList[group];
      imgGroup.splice(imgGroup.indexOf(el.src), 1);
    }
 }
}

`
所以一直不知道为什么VUE没有把第二个EL删除掉  而是删除了最后一个元素，然后把其余的数据填充上去了而已

**Comment by ssshooter** [comment]
哦...你是纠结删掉了最后一个元素而不是展示效果有问题？
因为我的 key 绑定的是` :key="src + index"` 😂 当时为了避免重复 url 的问题

**Comment by liqingjie** [comment]
在ios的中显示图片没在中间 而在下方请问是什么原因？

**Comment by ssshooter** [comment]
@liqingjie 麻烦提供一下截图

**Comment by elevenyes** [comment]
> 哦...你是纠结删掉了最后一个元素而不是展示效果有问题？
> 因为我的 key 绑定的是` :key="src + index"`  当时为了避免重复 url 的问题

就是展示有问题，他的例子原数组删除的是第二张，结果预览数组里删除的是第四张。导致原本第四张应该正常预览的无法预览，反而第二张可以预览

**Comment by elevenyes** [comment]
> > 哦...你是纠结删掉了最后一个元素而不是展示效果有问题？
> > 因为我的 key 绑定的是` :key="src + index"`  当时为了避免重复 url 的问题
> 
> 就是展示有问题，他的例子原数组删除的是第二张，结果预览数组里删除的是第四张。导致原本第四张应该正常预览的无法预览，反而第二张可以预览

找到原因了，确实不能以index作为key的值，不然预览视图不会更新!
