### ISSUE TITLE
在ios中图片高度不及屏幕高度时，图片显示在下方，没有居中

### ISSUE THREAD

**Issue by liqingjie** [ssshooter/img-vuer#13]
![img_20180709_175827](https://user-images.githubusercontent.com/29447855/42444519-e6c563d0-83a2-11e8-92f6-85f1df5a0008.jpg)

**Comment by ssshooter** [comment]
....这边的设备重现不了

**Comment by liqingjie** [comment]
...好尴尬。

**Comment by ssshooter** [comment]
或者能不能打包一个出问题的demo给我？

**Comment by liqingjie** [comment]
http://365edian.com/mall/  你可以通过ipone访问这个地址。在【店铺】-【店铺详情】里面有一个【电气秀】，可以看到。

**Comment by ssshooter** [comment]
更新到最新版本试试？

**Comment by liqingjie** [comment]
更新后没有这个问题了。感谢

**Comment by ssshooter** [comment]
👌
