### ISSUE TITLE
手动控制关闭图片预览问题

### ISSUE THREAD

**Issue by xiaohuahao** [ssshooter/img-vuer#15]
请问可以手动关闭图片预览吗？我使用`gallery.closeGallery()`和`document.querySelector('.slider').className = 'slider close'`都可以实现关闭图片预览，但是当重新点击图片的时候却不能弹出预览的图片，请问这个该怎么处理呢，谢谢大牛不吝赐教。

**Comment by ssshooter** [comment]
设计上的失误，确实应该暴露关闭接口:joy:
会在今天内更新:joy:

**Comment by ssshooter** [comment]
@xiaohuahao 可以简单描述一下使用场景吗？

**Comment by xiaohuahao** [comment]
使用场景，就是当图片预览的时候点击安卓手机的物理返回键，把预览图片关闭。

**Comment by ssshooter** [comment]
自己处理物理返回键还是挺麻烦的，如果是返回问题的话需求就跟暴露关闭接口不一样了，
或者我直接处理物理返回键关闭图片的问题吧？

**Comment by xiaohuahao** [comment]
直接暴露关闭接口就可以了，物理返回键的逻辑处理可能会不一样，统一处理的话不是很好扩展。

**Comment by ssshooter** [comment]
https://github.com/ssshooter/img-vuer/blob/a2d0dd8a53b080d0ea1b51eee2a58a3a4ddb5ec1/src/Vuer.vue#L58

认真想了一下还是觉得关闭接口应用场景很有限，所以更新物理键返回吧，如果有设备不适配再作调整

**Comment by xiaohuahao** [comment]
我使用努比亚手机测试了一下，点击物理返回键直接会返回上个页面，当然预览页面也会关闭。

**Comment by xiaohuahao** [comment]
点击物理返回键好像不能关闭预览页面。

**Comment by ssshooter** [comment]
emmmm 请问原计划中拦截努比亚物理返回的代码是怎样的？

**Comment by xiaohuahao** [comment]
我是直接使用的路由处理的，`router.beforeEach((to, from, next) => {
    var className = document.querySelector('.slider').className
    if (className === 'slider open') {
      next(false)
    } else  {
      next()
    }
})`

**Comment by ssshooter** [comment]
这样的话如果用户没有使用 vue-router 就无效了...
可以帮忙看一下努比亚的 `navigator.userAgent` 打印出来是什么吗？

**Comment by cotv** [comment]
关闭接口怎么弄啊？

**Comment by ssshooter** [comment]
@cotv 什么场景？
