### ISSUE TITLE
长图显示的时候模糊

### ISSUE THREAD

**Issue by hhhippo** [ssshooter/img-vuer#16]
请问在长图显示的时候模糊这个怎么解决呢

**Comment by ssshooter** [comment]
如何模糊？

**Comment by hhhippo** [comment]
例如一张长度远远比宽度大的图片，虽然可以显示但是双指放大后发现图片的清晰度下降得厉害

**Comment by hhhippo** [comment]
PC也有这个问题的，局部强制放大以后才局部清晰，

**Comment by shoung6** [comment]
好像是因为长图的实际长比如有10000px，但是我们的img标签高只有1000px。transform放大也是会糊的。
我的想法是初始化时用两倍屏幕高的img来渲染并缩放50%。就能处理大部分的长图了。

**Comment by shoung6** [comment]
> 找到一个 hack，实测有效
> 添加 `transform: translateZ(0);` 对动画使用硬件加速
> https://stackoverflow.com/questions/14677490/blurry-text-after-using-css-transform-scale-in-chrome
> 
> PS: safari 还是不行
我上面提到的思路能否行的通啊，好像改动蛮大

**Comment by ssshooter** [comment]
嗯，行得通，但改动很大

**Comment by shoung6** [comment]
> 嗯，行得通，但改动很大

我看了下微信的查看大图，点开了初始状态是图片宽度占满屏幕的~

**Comment by ssshooter** [comment]
垂直长图也是高度占满呀 ❓

**Comment by ssshooter** [comment]
@hhhippo @shoung6 v0.15.0 已修复此问题 😂

**Comment by shoung6** [comment]
> @hhhippo @shoung6 v0.15.0 已修复此问题 😂

୧(๑•̀◡•́๑)૭

**Comment by hhhippo** [comment]
> @hhhippo @shoung6 v0.15.0 已修复此问题 😂

佩服୧(๑•̀◡•́๑)૭

**Comment by shoung6** [comment]
> @hhhippo @shoung6 v0.15.0 已修复此问题 😂

demo里不搞个长图演示下嘛~其他库也很多不支持

**Comment by ssshooter** [comment]
> > @hhhippo @shoung6 v0.15.0 已修复此问题 😂
> 
> demo里不搞个长图演示下嘛~其他库也很多不支持

好主意√
