### ISSUE TITLE
魅族自带浏览器调不起预览图片

### ISSUE THREAD

**Issue by 6337215** [ssshooter/img-vuer#19]
发现个比较尴尬的问题，一般手机浏览器可以，就是在魅族手机魅蓝note系列和华为一些低端的手机自带浏览器，无法打开预览图片，已经有了slider open这个类名，但是预览图片也没有显示出来

**Comment by ssshooter** [comment]
试了一下手边的魅蓝 metal，Flyme 6.3.0.2A， 浏览器 7.6.2，似乎正常...

**Comment by 6337215** [comment]
好吧~今天下午试了试，结果又可以了，谢谢哈，这个插件挺好用到，之前本想封装一个，结果怎么都不满意

**Comment by ssshooter** [comment]
😄可以就好
