### ISSUE TITLE
滑动换图太费劲

### ISSUE THREAD

**Issue by tuotool** [ssshooter/img-vuer#2]
组件很不错，提个小建议，图片切换也太难了，几乎要从屏幕的一个边缘直拖到另一个边缘，返回也不明显。

另外二维码是用的哪个组件生成的？挺漂亮。

**Comment by ssshooter** [comment]
@tuotool 
其实图片切换要划大半个屏幕是模仿我的手机原生图库的手感，如果大家觉得划太远不方便的话就还是改短一点吧。
返回不明显的意思是？
二维码是用的是联图网生成的😂

**Comment by naclank** [comment]
图片切换确实需要划比较长的距离，怎么改这个设置呢？

**Comment by ssshooter** [comment]
https://github.com/ssshooter/img-vuer/blob/a9f3ba7aeacf5358a3c9effa2582a584abe09871/src/Vuer.vue#L86-L97

这一块，改100就行

**Comment by ssshooter** [comment]
emmmm.....可能跟下面一层的手势代码有关.....下个版本整合到一起好了
