### ISSUE TITLE
Can I have an access to current image index?

### ISSUE THREAD

**Issue by tsyrya** [ssshooter/img-vuer#21]
Hello,

I would really appreciate if you make it possible to have an access to the current image index.

thank you

**Comment by tsyrya** [comment]
I actually need to know when user changes the picture and do some things, is that possible?

**Comment by ssshooter** [comment]
Oh, passing the callback function to installer is able to implement this.

**Comment by tsyrya** [comment]
Maybe u can emit the event using EventBus?

**Comment by ssshooter** [comment]
But it require a extra instance 😂

**Comment by ssshooter** [comment]
now you can access current index use `this.$imgVuer.getCurrentIndex()`
