### ISSUE TITLE
我v-for 删除其中一张图片之后，再点击放大，好像不会自动删除你放大的图片

### ISSUE THREAD

**Issue by DexSinis** [ssshooter/img-vuer#22]

**Comment by ssshooter** [comment]
测试是可以的，你删除操作是怎样的？

**Comment by DexSinis** [comment]
移除数组中的一个数据，          
<div class="upload-img-list">
            <span v-for="item in pic"><i @click="removeImg(item.showPath)"></i><img  v-gallery:groupName :src="item.showPath"> </span>
 </div>

大概这样，更新pic数组之后，就是删除一个之后，这个点击打开，放大的图片的div没有跟着改变

**Comment by ssshooter** [comment]
暂时关闭，有问题可随时重开

**Comment by elevenyes** [comment]
我也遇到了类似的问题，删除多张图片的时候，我这边的图片数组是删除正确了，但是预览数组是删除的原图片数组的最后一张，导致最后一张无法预览，反正删除的那一张还在预览数组里面

**Comment by DexSinis** [comment]
<div class="upload-img-list">
          <span v-for="item in pic"><i @click="removeImg(item.showPath)"></i><img :src="item.showPath"> </span>
        </div>


      removeImg(showPath) {
        let index = -1;
        for (let i = 0; i < this.pic.length; i++) {
          if (showPath == this.pic[i].showPath) {
            index = i;
          }
        }
        this.pic.splice(index, 1);
      }

我的写法是这样的，好像没问题，参照一下

**Comment by elevenyes** [comment]
<div class="img-list" v-for="(item,index) in imgList" :key="index">
                <img :src="item.imgUrl" v-gallery="tit" alt="">
                <i :id="item.imgId" @click="deleteImg(index, item.imgId)"></i>
            </div>
deleteImg(index,id){
this.imgList.splice(index,1)
}
我是这样写的，不行。我图片展示循环数组是已经删除对应的图片了，但是点开删除后数组的最后一张无法预览，左右拖动还能看到原数组已经删除的那一张

> ```
>    <div class="upload-img-list">
>           <span v-for="item in pic"><i @click="removeImg(item.showPath)"></i><img :src="item.showPath"> </span>
>         </div>
> ```
> 
> ```
>       removeImg(showPath) {
>         let index = -1;
>         for (let i = 0; i < this.pic.length; i++) {
>           if (showPath == this.pic[i].showPath) {
>             index = i;
>           }
>         }
>         this.pic.splice(index, 1);
>       }
> ```
> 
> 我的写法是这样的，好像没问题，参照一下

<div class="img-list" v-for="(item,index) in imgList" :key="index">
                <img :src="item.imgUrl" v-gallery="tit" alt="">
                <i :id="item.imgId" @click="deleteImg(index, item.imgId)"></i>
            </div>
deleteImg(index,id){
this.imgList.splice(index,1)
}
我是这样写的，不行。我图片展示循环数组是已经删除对应的图片了，但是点开删除后数组的最后一张无法预览，左右拖动还能看到原数组已经删除的那一张

**Comment by elevenyes** [comment]
<div class="img-list" v-for="(item,index) in imgList" :key="index">
                <img :src="item.imgUrl" v-gallery="tit" alt="">
                <i :id="item.imgId" @click="deleteImg(index, item.imgId)"></i>
            </div>
deleteImg(index,id){
this.imgList.splice(index,1)
}
我是这样写的，不行。我图片展示循环数组是已经删除对应的图片了，但是点开删除后数组的最后一张无法预览，左右拖动还能看到原数组已经删除的那一张
