### ISSUE TITLE
多图滑动问题

### ISSUE THREAD

**Issue by leeww** [ssshooter/img-vuer#24]
我这是一个商品列表，每一个商品有多个图片，可以预览，代码如下，id是商品的id按理来说是可以分不同的gallery的，现在预览的时候，可以预览到别的商品的图片，0.15.0之前是好使的，看了gallery.js做了一些String()的修改，不知道是不是有影响，麻烦看一下
        `<div 
                v-for="(img,index) in data.goods.imgs"
                :key="'img'+data.goods.id+index" 
                class="img-wrapper" 
            >
                <img 
                    v-gallery:data.goods.id
                    :src="common.handleImgUrl(img)" 
                    alt="商品图片">
            </div>`

**Comment by leeww** [comment]
是这里的问题。gallery.js里面以前没有String()，现在是`let group = String(binding.arg) || binding.value`，想问为什么要这么改呀？

**Comment by ssshooter** [comment]
低级错误，抱歉

**Comment by ssshooter** [comment]
v0.15.3 已修复
