### ISSUE TITLE
无法自动生成binding.arg，调用方式有疑问

### ISSUE THREAD

**Issue by 62006464** [ssshooter/img-vuer#3]
<  img class="item-pic" v-gallery:groupName :group1="item.id" :src="p.url" v-for="p in item.more['photos']">
跟v-for一起用的时候，group无法自定义的。下面这样，好像可以解决，貌似有点不美。 作者有什么方案吗？

`
inserted(el, binding) {
        let group = binding.value.arg
        // console.log(binding);
        el.addEventListener('click', handleClick(el, group))
       。。。
}
`
< img v-gallery="{arg:'groupName‘}"
          class="thumbnail"
          v-for="(item,index) in list1"
          :src="item.src"
          :key="item.src" >

**Comment by ssshooter** [comment]
emmm之前没考虑过这个问题...想想这个问题也挺大的，谢谢提醒！
这个位置是没办法动态传参数的，如果要要再包一层div来传参就更难看了，     
不过要考虑暂时没有其他参数的话，直接这样是不是简洁点` v-gallery="groupName"`？

**Comment by 62006464** [comment]
是啊，很简洁了  等你早点修复这个问题哟

**Comment by ssshooter** [comment]
0.9.18 已更新

**Comment by 62006464** [comment]
👍
