### ISSUE TITLE
iphoneX 不兼容

### ISSUE THREAD

**Issue by AugustEM** [ssshooter/img-vuer#31]
iphoneX 点击预览刷新页面，无法预览

**Comment by ssshooter** [comment]
意思是：进入预览后，刷新页面，然后就不能再预览了？

**Comment by AugustEM** [comment]
就是iphoneX点击图片预览就会刷新页面，点一次刷新一次，刷新了预览效果就没有了

**Comment by ssshooter** [comment]
其他手机都没有这个现象？

**Comment by AugustEM** [comment]
iphoneX以下的没有问题，可能是新机型兼容性吧，iphoneX在微信内置浏览器会这样

**Comment by luanzhuxian** [comment]
微信内 iphoneX 和 iphone6S 预览图片都会刷新页面

**Comment by luanzhuxian** [comment]
好像是图片体积较大时才会出现刷新的问题
