### ISSUE TITLE
在某些情况下出现多张图无法拖动

### ISSUE THREAD

**Issue by xpader** [ssshooter/img-vuer#32]
今天出现页面中有两张图，而且是同一个组，点第一张图无法左右拖动，点第二张图就就可以拖动了，然后再点第一张图就可以拖动。

反复尝试，都是初次打开时点第一张图会无法拖动。

研究了一下源码，我看到了 VueSingle.vue 内部是通过计算宽度来决定 emit disableSwipe 或者 enableSwipe 事件的，而这两个事件就决定了 Vuer.vue 里的 allowSwipe 变量的值，这个变量的值又决定能否拖动。

可能页面内的图片宽高正好处于一个微妙的状态，导致内部计算不正确，我目前发现最方便的方法是将 Vuer.vue 里的 allowSwiper 变量改为 computed 属性，值根据 imgList 的长度是否超过 1 来决定是否能滚动。
`    allowSipe() {
      return this.imgList.length > 1;
    }`

我不清楚这样改会不会有什么问题，但是这样改解决了我的问题。

希望作者能修复这个问题。

**Comment by xpader** [comment]
By the way，第一张图是张屏幕截图，属于比较高，第二张图是横着拍照的图，是比较宽的。

**Comment by ssshooter** [comment]
无法重现...用大小和屏幕相同的图片测试过

```javascript
      if (
        el.scaleX / this.initialScale < 1.2 &&
        el.scaleX / this.initialScale > 0.8
      ) {
        this.$emit('enableSwipe')
        el.translateX += e.deltaX / 3
        return
      }
```

其实在实现上图片宽度影响$emit('enableSwipe')有一个区间，所以应该没问题 😢

**Comment by xpader** [comment]
我这里只要两张图片就必现，iPhone 6s 竖屏截图再一张横屏的拍照就必现。

**Comment by shby0527** [comment]
重现 @ssshooter 图片宽度小于屏幕宽度后，就无法到下一张图了，点开后面的图后滑动到前面的小图，再进行一次缩放动作后，亦不可拖动。

**Comment by ssshooter** [comment]
感谢 @shby0527
