### ISSUE TITLE
img-vuer lack of initialization function

### ISSUE THREAD

**Issue by Penguin-Lin** [ssshooter/img-vuer#49]
![part1](https://user-images.githubusercontent.com/33897969/63821854-18781d80-c981-11e9-9212-c570444204c6.png)
____________________________________________________________________________________
![part2](https://user-images.githubusercontent.com/33897969/63821938-54ab7e00-c981-11e9-9524-779be046ef5d.jpg)
When i enter the first page, the numbers of big picture is correct. However when i enter the second page, the numbers is wrong. It's seems to add imgs after the first time. How can i fix that?

**Comment by ssshooter** [comment]
Those 5 images are in the same group now, you should split them to two array.
