### ISSUE TITLE
关闭预览时显示图片序号的div仍然存在导致遮挡了其他DIV

### ISSUE THREAD

**Issue by amnextking** [ssshooter/img-vuer#56]
关闭预览时显示图片序号的div仍然存在导致遮挡了其他DIV
![image](https://user-images.githubusercontent.com/11473678/71139519-59a27f00-2249-11ea-8e3f-bdb93e334e4e.png)

**Comment by ssshooter** [comment]
0.19.1应该解决了这个问题，是还在用之前的版本吗？

**Comment by amnextking** [comment]
是的 后来解决了这个问题说提个PR 结果发现有人发现的更早
