### ISSUE TITLE
cannot show big images for mobile view on click!

### ISSUE THREAD

**Issue by Medala** [ssshooter/img-vuer#63]
On a normal view, you can see this image https://demos.imgix.net/wristwatch.jpg but on click does not show the image. If an inline width is given https://demos.imgix.net/wristwatch.jpg?w=500 or more, it goes to the side and out of view.

**Comment by ssshooter** [comment]
![image](https://user-images.githubusercontent.com/13051472/93571565-39b20e80-f9c7-11ea-8019-c1f84ffbdcd6.png)
![image](https://user-images.githubusercontent.com/13051472/93571593-420a4980-f9c7-11ea-8ff7-92b50e5f3c55.png)
It seems working fine 😂

**Comment by Medala** [comment]
😆 maybe it's a problem with my browser. I'll close it then.
