### ISSUE TITLE
图片放大操作范围

### ISSUE THREAD

**Issue by sunlij** [ssshooter/img-vuer#9]
放大图片的手势， 操作范围似乎是在图片范围，图片外放大手势无效。这样做如果图片是很细的一条，是否操作不便？
还有如果原本图片就是很小的一张，似乎会等比放大到全屏，这样处理好吗？如果图片很小就原大小居中展示这样处理可以不。

**Comment by ssshooter** [comment]
好提议....我想想怎么实现:joy:

**Comment by ssshooter** [comment]
img-vuer 0.10.0 添加此功能:joy:

**Comment by sunlij** [comment]
厉害了！
